BugTracker/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Async;


namespace BugTracker.Controllers
{
    public class AccountsController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }
        // GET: Accounts
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            if (username == "aman" && password == "iacsd")
            {
                return this.RedirectToAction("index", "home");
            }
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }





     /*   [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult MagesticLogin(LoginViewModel model,string returnUrl)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }


            var result = await SignInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe, shouldLockout: false);
            switch(result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(returnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.RequiresVerification:
                    return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid Login attempt");
                    return View(model);
            }
        }



        public ActionResult MajesticLogin(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        */
    }
}

BugTracker/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BugTracker.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ManageRole()
        {
            return View();
        }

        public ActionResult Projects()
        {
            return View();
        }

        public ActionResult Tickets()
        {
            return View();
        }

        public ActionResult Users()
        {
            return View();
        }
    }
}

BugTracker/Controllers/ManageRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BOL;
using BLL;

namespace BugTracker.Controllers
{
    public class ManageRoleController : Controller
    {
        // GET: ManageRole
        public ActionResult Index()
        {
            List<string> managers = new List<string>();
            managers.Add("gerbera");
            managers.Add("gerbera");
            managers.Add("gerbera");
            managers.Add("gerbe");
            this.ViewData["managers"] = managers;


            // List<Product> PP = new List<Product>();


            //  flowers = BuisnessManager.GetAllProducts();
            //  this.ViewData["flowers"] = flowers;

            List<Manager> allManagers = BusinessManager.GetAllManagers();
            this.ViewData["managers"] = allManagers;
            return View();
        }

        public ActionResult Details(int id)
        {
            Manager theManager = BusinessManager.GetManager(id);
            return View(theManager);

        }


        public ActionResult InsertM()
        {
            return View();
        }


        [HttpPost]
        public ActionResult InsertM(int Id, string MName, string Email,
                                string Role)
        {
            Manager newManager = new Manager
            {
                Id = Id,
                MName = MName,
                Email = Email,
                Role = Role,
                //Quantity = quantity,
                //ImageUrl = imageurl
            };

            bool status = BusinessManager.InsertM(newManager);
            if (status)
            {
                this.RedirectToAction("index", "managers");
            }
            return View();
        }



        public ActionResult UpdateM(int Id)
        {
            Manager existingManager = BusinessManager.GetManager(Id);
            return View(existingManager);
        }

        [HttpPost]
        public ActionResult UpdateM(Manager modifiedManager)
        {
            TryValidateModel(modifiedManager);
            if (ModelState.IsValid)
            {
                bool status = BusinessManager.UpdateM(modifiedManager);
                if (status)
                {
                    return this.RedirectToAction("index", "managers");
                }
            }
            return View();
        }

    }
}

BugTracker/Controllers/ManagersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BugTracker.Controllers
{
    public class ManagersController : Controller
    {
        // GET: Managers
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details()
        {
            return View();
        }
    }
}

BugTracker/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BugTracker.Controllers
{
    public class ProjectsController : Controller
    {
        // GET: Projects
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ManageUser()
        {
            return View();
        }

        public ActionResult Details()
        {
            return View();
        }
    }
}

BugTracker/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BugTracker.Controllers
{
    public class TicketsController : Controller
    {
        // GET: Tickets
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult Edit()
        {
            return View();
        }

        public ActionResult Update()
        {
            return View();
        }

    }
}

BugTracker/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BugTracker.Controllers
{
    public class UsersController : Controller
    {
        // GET: Users
        public ActionResult Index()
        {
            return View();
        }
    }
}

BugTracker/Views/Accounts/Index.cshtml
@{
    ViewBag.Title = "Index";
}

 
<!doctype html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Bug Tracker </title>
    <link rel="stylesheet" href="~/Style/Style2.css" />
    <link rel="stylesheet" href="~/Style/Style3.css" />
</head>
<body>
        

                <section>
                    <video src="~/Content/src/d.mp4" autoplay="" muted="" loop=""></video>
                </section>
                <section>
                    <div class="content">
                        <h2>
                            Bug Tracker
                        </h2>
                        <p>Bug Tracker will resolve the error.Step into the system.</p>

                        <a href="/Accounts/Login"> Login </a>
                        <a href="#"> Register </a>
                        <p>
                            The Year 2000 problem, also known as the Y2K problem, the Millennium bug, Y2K bug, the Y2K glitch, or Y2K, refers to events related to the formatting and storage of calendar data for dates beginning in the year 2000. Problems were anticipated, and arose, because many programs represented four-digit years with only the final two digits – making the year 2000 indistinguishable from 1900. The assumption of a twentieth-century date in such programs could cause various errors, such as the incorrect display of dates and the inaccurate ordering of automated dated records or real-time events.

                            In 1997, the British Standards Institute (BSI) developed standard DISC PD2000-1 defining "Year 2000 Conformity requirements" as four rules:

                            No valid date will cause any interruption in operations.
                            Date-based functionality must behave consistently for dates prior to, during and after year 2000.
                            In all interfaces and in all storage, the century must be unambiguous, either specified, or calculable by algorithm.
                            Year 2000 must be recognised as a leap year.
                            It identifies two problems that might exist in many computer programs. First, the practice of representing the year with two digits became problematic with logical error(s) arising upon "rollover" from xx99 to xx00. This had caused some date-related processing to operate incorrectly for dates and times on and after 1 January 2000, and on other critical dates which were billed "event horizons". Without corrective action, long-working systems would break down when the "... 97, 98, 99, 00 ..." ascending numbering assumption suddenly became invalid.

                            Secondly, some programmers had misunderstood the Gregorian calendar rule that states years that are exactly divisible by 100 are not leap years, assuming that the year 2000 would not be a leap year. While this is true, there is an exception that states years divisible by 400 are leap years – thus making 2000 a leap year.

                            Correcting all of this, however, was not the largest part of the problem. By 1997, AT&T had estimated that "60% of the time and money needed for its total compliance efforts" would be devoted to testing the source code changes made to address the issue.

                            Companies and organisations in some countries, but not all, checked, fixed, and upgraded their computer systems to address the anticipated problem.Very few computer failures were reported when the clocks rolled over into 2000.
                        </p>
                    </div>

                </section>
                <script type="text/javascript">
                    let video = document.querySelector('video');
                    window.addEventListener('scroll', function () {
                        let value = 1 + window.scrollY / -600;
                        video.style.opacity = value;
                    })
                </script>
                <script type="text/javascript">
                    const buttons = document.querySelectorAll('a');
                    buttons.forEach(btn => {
                        btn.addEventListener('click', function (e) {
                            let x = e.clientX - e.target.offsetLeft;
                            let y = e.clientY - e.target.offsetTop;
                            let ripples = document.createElement('span');
                            ripples.style.left = x + 'px';
                            ripples.style.top = x + 'px';
                            this.appendChild(ripples);

                            setTimeOut(() => {
                                ripples.remove()
                            }, 1000);
                        })
                    })

                </script>

</body>
</html>

BugTracker/Views/Accounts/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
<form method="post">
    User Name <input type="text" name="username" />
    Password <input type="password" name="password" />
    <button type="submit">Login</button>
</form>
<a href="/accounts/register">Register</a>


<!doctype html>
<html>
<head>
    <title>Majestic Login Form Flat Responsive widget Template :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Majestic Login Form Widget Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- font files -->
    <link href='//fonts.googleapis.com/css?family=Muli:400,300,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Comfortaa:400,300,700' rel='stylesheet' type='text/css'>
    <!-- /font files -->
    <!-- css files -->
    <link href="~/w3/majestic/css/animate-custom.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/w3/majestic/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- /css files -->
</head>
<body>
    <h1 class="w3ls">Y2K Bug Tracker Login Form</h1>
    <div id="container_demo">
        <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
        <a class="hiddenanchor" id="toregister"></a>
        <a class="hiddenanchor" id="tologin"></a>
        <div id="wrapper">
            <div id="login" class="animate form">
             
                {
                <form method="post">
                    <h2>Log in</h2>
                    <p>
                        <label for="username" class="uname" data-icon="u"><span>Your Username</span></label>
                        <input id="username" name="username" required="required" type="text" placeholder="EMAIL OR USERNAME" />

                    </p>
                    <p>
                        <label for="password" class="youpasswd" data-icon="p"><span>Your password</span></label>
                        <input id="password" name="password" required="required" type="password" placeholder="eg. X8df!90EO" />

                    </p>
                    <p>
                        <input type="checkbox" id="brand" value="">

                        <label for="brand"><span></span> Remember me?</label>
                    </p>
                    <p class="login button">
                        <input type="submit" value="Login" />
                    </p>
                    <p class="change_link">
                        <span>Not a member yet ?</span>
                        <a href="#toregister" class="to_register">Register Now</a>
                    </p>

                </form>
                }
              
            </div>
            <div id="register" class="animate form">
                <form action="#" method="post" autocomplete="on">
                    <h2> Sign up </h2>
                    <p>
                        <label for="usernamesignup" class="uname" data-icon="u"><span>Your name</span></label>
                        <input id="usernamesignup" name="usernamesignup" required="required" type="text" placeholder="USERNAME" />
                    </p>
                    <p>
                        <label for="emailsignup" class="youmail" data-icon="e"><span>Your email</span></label>
                        <input id="emailsignup" name="emailsignup" required="required" type="email" placeholder="EXAMPLE@MAIL.COM" />
                    </p>
                    <p>
                        <label for="passwordsignup" class="youpasswd" data-icon="p"><span>Your password</span></label>
                        <input id="passwordsignup" name="passwordsignup" required="required" type="password" placeholder="eg. X8df!90EO" />
                    </p>
                    <p>
                        <label for="passwordsignup_confirm" class="youpasswd" data-icon="p"><span>Please confirm your password</span></label>
                        <input id="passwordsignup_confirm" name="passwordsignup_confirm" required="required" type="password" placeholder="eg. X8df!90EO" />
                    </p>
                    <p class="signin button">
                        <input type="submit" value="Sign up" />
                    </p>
                    <p class="change_link">
                        <span>Already a member ?</span>
                        <a href="#tologin" class="to_register">Log In</a>
                    </p>
                </form>
            </div>
        </div>
    </div>
    <p class="agileits">© 2016 Majestic Login Form. All Rights Reserved | Design by <a href="https://w3layouts.com/" target="_blank">w3layouts</a></p>
</body>
</html>

BugTracker/Views/Accounts/MajesticLogin.cshtml
@model MvcDemo.Models.LoginViewModel
@{
    // ViewBag.Title = "MajesticLogin";
    Layout = null;
}

<!doctype html>
<html>
<head>
    <title>Majestic Login Form Flat Responsive widget Template :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Majestic Login Form Widget Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login signup Responsive web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- font files -->
    <link href='//fonts.googleapis.com/css?family=Muli:400,300,300italic,400italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Comfortaa:400,300,700' rel='stylesheet' type='text/css'>
    <!-- /font files -->
    <!-- css files -->
    <link href="~/w3/majestic/css/animate-custom.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/w3/majestic/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- /css files -->
</head>
<body>
    <h1 class="w3ls">Majestic Login Form</h1>
    <div id="container_demo">
        <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
        <a class="hiddenanchor" id="toregister"></a>
        <a class="hiddenanchor" id="tologin"></a>
        <div id="wrapper">
            <div id="login" class="animate form">
                @using (Html.BeginForm("MajesticLogin", "Account", FormMethod.Post, new { @autocomplete = "on" }))
                {
                    @Html.AntiForgeryToken()
                    <h2>Log in</h2>
                    <p>
                        <label for="username" class="uname" data-icon="u"><span>Your Username</span></label>
                        @Html.TextBoxFor(m => m.UserName, new { @placeholder = "Username" })
                    
                                          </p>
                    <p>
                        <label for="password" class="youpasswd" data-icon="p"><span>Your password</span></label>
                       
                        @Html.PasswordFor(m=>m.Password,new { @placeholder= "eg. X8df!90EO" })
                    </p>
                    <p>
                        <input type="checkbox" id="brand" value="">
                        @Html.CheckBoxFor(m => m.RememberMe, new { @id= "brand" })
                        <label for="brand"><span></span> Remember me?</label>
                    </p>
                    <p class="login button">
                        <input type="submit" value="Login" />
                    </p>
                    <p class="change_link">
                        <span>Not a member yet ?</span>
                        <a href="#toregister" class="to_register">Register Now</a>
                    </p>

                }
              
            </div>
            <div id="register" class="animate form">
                <form action="#" method="post" autocomplete="on">
                    <h2> Sign up </h2>
                    <p>
                        <label for="usernamesignup" class="uname" data-icon="u"><span>Your name</span></label>
                        <input id="usernamesignup" name="usernamesignup" required="required" type="text" placeholder="USERNAME" />
                    </p>
                    <p>
                        <label for="emailsignup" class="youmail" data-icon="e"><span>Your email</span></label>
                        <input id="emailsignup" name="emailsignup" required="required" type="email" placeholder="EXAMPLE@MAIL.COM" />
                    </p>
                    <p>
                        <label for="passwordsignup" class="youpasswd" data-icon="p"><span>Your password</span></label>
                        <input id="passwordsignup" name="passwordsignup" required="required" type="password" placeholder="eg. X8df!90EO" />
                    </p>
                    <p>
                        <label for="passwordsignup_confirm" class="youpasswd" data-icon="p"><span>Please confirm your password</span></label>
                        <input id="passwordsignup_confirm" name="passwordsignup_confirm" required="required" type="password" placeholder="eg. X8df!90EO" />
                    </p>
                    <p class="signin button">
                        <input type="submit" value="Sign up" />
                    </p>
                    <p class="change_link">
                        <span>Already a member ?</span>
                        <a href="#tologin" class="to_register">Log In</a>
                    </p>
                </form>
            </div>
        </div>
    </div>
    <p class="agileits">© 2016 Majestic Login Form. All Rights Reserved | Design by <a href="https://w3layouts.com/" target="_blank">w3layouts</a></p>
</body>
</html>

BugTracker/Views/Accounts/Register.cshtml
@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>

<h2>Fill Register Form</h2>

BugTracker/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<hr/>
<link href="~/Style/Style.css" rel="stylesheet" type="text/css" />

<ul>
    <li data-text="Manage Role Assigment"><a href="/ManageRole">Manage Role Assigment</a></li> 
    <li data-text="My Projects"><a href="/Projects">My Projects</a></li>
    <li data-text="My Tickets"><a href="/Tickets">My Tickets</a></li>  
    <li data-text="My Users"><a href="/Users">My users</a></li> 
</ul>

BugTracker/Views/ManageRole/Details.cshtml
@using BOL;
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/sideBar.cshtml";
}



<h2>Details of the Managers</h2>

<hr />
@{
     Manager theManager = Model as Manager;

    // <img src="@theProduct.ImageUrl" width="100" height="100" />

    <p>Id : @theManager.Id</p>
    <p>Manager Name : @theManager.MName</p>
    <p>Email - ID : @theManager.Email</p>
    <p>Role : @theManager.Role</p>
    //  <p>Quantity: @theProduct.Quantity</p>

    //  <a href="/shoppingcart/addtocart/@theProduct.ID">Add to Cart</a>
}

BugTracker/Views/ManageRole/Index.cshtml
@using BOL;
@{
    ViewBag.Title = "Index";
    // ViewBag.Title1 = "Index";
    Layout = "~/Views/Shared/sideBar.cshtml";

}

<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Bug Tracker </title>
    
    <link rel="stylesheet" href="~/Style/Style4.css" />
</head>
<body>




    <div id="parent">
        <div id="left">

            <h3>Manage User Role</h3>
            <a href="~/Tickets2.aspx" role="button" class="btn btn-success btn-large">Manage</a>

            <h3>Select Role To Assign</h3>
            <a href="~/Users.aspx" role="button" class="btn btn-success btn-large">Users</a>

            <h3>Assigned Personell</h3>
            <a href="~/Tester.aspx" role="button" class="btn btn-success btn-large">Testers</a>
        </div>
        <div id="right">

            <h3>Available of Managers</h3>

            <ol>
                @{
                     //@flower.Title
                     List <Manager> managers = (List<Manager>)this.ViewData["managers"];
                    foreach (Manager manager in managers)
                    {
                        <table> <tr><td><a href="/managerole/Details/@manager.Id">@manager.MName</a></td></tr> </table>


                        //   <a href="/managerole/Details/@manager.Id">@manager.MName</a>

                    }
                }

            </ol>




        </div>
    </div>




    <div class="container" align="left" width="40%">






    </div>

    <br />
    <div class="container" align="right" width="50%">




    </div>
    </body>
</html>

BugTracker/Views/ManageRole/InsertM.cshtml
@{
    ViewBag.Title = "InsertM";
    Layout = "~/Views/Shared/sideBar.cshtml";
}

<h2>Insert The Manager</h2>

 

 
<form method="post">
    <table>
        <tr><td>   ID:  </td> <td><input type="text" name="Id" /> </td>    </tr>
        <tr><td>   Manager Name : </td><td> <input type="text" name="MName" />  </td></tr>
        <tr><td>   Email-Id: </td><td> <input type="text" name="Email" />    </td></tr>
        <tr><td>  Address: </td><td> <input type="text" name="Role" />  </td></tr>
        <tr><td>  <button type="submit" class="btn-success">Insert</button></td></tr>

</table>
   
   
   
   

</form>

BugTracker/Views/ManageRole/UpdateM.cshtml
@{
    ViewBag.Title = "UpdateM";
}

<h2>UpdateM</h2>

<form method="post">
    ID:  <input type="text" name="Id" />
    Manager Name :  <input type="text" name="MName" />
    Email:  <input type="text" name="Email" />
    Role:  <input type="text" name="Role" />

    <button type="submit">Update</button>
</form>

BugTracker/Views/Managers/Details.cshtml
@using BOL;
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/sideBar.cshtml";
}



<h2>Details of the Managers</h2>

 

BugTracker/Views/Projects/Details.cshtml
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<a href="/Tickets">More Details</a>

BugTracker/Views/Projects/ManageUser.cshtml
@{
    ViewBag.Title = "ManageUser";
}

<h2>ManageUser</h2>

<p>hello</p>

BugTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
 
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Y2K BUG-TRACKER", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Manager Role", "Index", "ManageRole", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Projects", "Index", "Projects", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Users", "Index", "Users", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

   

    <div class="container body-content" >
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

BugTracker/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    
        <title>Y2K BUGTRACKER</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title1</title>
 </head>
   

<body>
    <div class="container">
            <table style="width:30%;" class="table table-dark table-hover">
            <tr><td>Logo</td></tr>
            <tr><td>Y2K BUGTRACKER</td></tr>
            <tr><td>DETAILS</td></tr>
            <tr><td>Left Side Bar</td><td>  @RenderBody()</td></tr>
        </table>
    </div>
</body>
</html>





 


  

BugTracker/Views/Tickets/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<h2>Edit your Ticket Here</h2>

BugTracker/Views/Tickets/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/sideBar.cshtml";
    // Layout = "~\Views\Shared\_LayoutPage1.cshtml";

}

 <html>
<head>




</head>
<body>

    <h2>Details of Ticket</h2><a href="/Tickets_html.aspx" class="btn btn-primary btn-large"> Details</a>
    <br />
    <br />
    <br />
    <a href="~/Bugs.aspx" role="button" class="btn btn-success btn-large"> Edit Tickets</a>

</body>
</html>

 


 

BugTracker/Views/Tickets/Update.cshtml
@{
    ViewBag.Title = "Update";
}

<h2>Update</h2>

<h2>Here you can update your ticket And see details for tickets </h2>
<a href="/Tickets/Edit">Edit/Assign</a>
<a href="/Tickets">Details</a>

BugTracker/Views/Users/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/sideBar.cshtml";

}
<html>
<head>

</head>
<body>
    <h2>All Users</h2><a href="~/UsersHTML.aspx" role="button" class="btn btn-primary btn-large">See Users</a>
    <a href="~/Users.aspx" role="button" class="btn btn-success btn-large">Users Details</a>
</body>



</html>